---
title: "ds 2003 proj"
output: html_document
date: "2023-10-14"
---

```{r}
# load libraries 
library(readr)
library(dplyr)
install.packages("viridis")
library(viridis)
```


```{r}
# cleaning data 
data <- read_csv("lifeexp.csv")

# remove corruption file, which has the most NAs 
rm_corruption <- data[-c(12)]

# rename all columns 
df_rename <- rm_corruption %>% 
        rename( "country" = "Country Name",
               "code" = "Country Code",
                "region" = "Region", 
                "inc" = "IncomeGroup",
                "year" = "Year",
                "lifespan" = "Life Expectancy World Bank",
                "starving" = "Prevelance of Undernourishment",
                "health" = "Health Expenditure %",
                "edu" = "Education Expenditure %",
                "unemp" = "Unemployment",
                "sanitation" = "Sanitation",
                "injury" = "Injuries",
                "comm" = "Communicable",
                "noncomm" = "NonCommunicable"
               )

df <- df_rename %>%
  group_by(region,year) %>%
  mutate(across(everything(), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)))
```



```{r}
ggplot(df, aes(x = year, y = inc, fill = health)) +
  geom_tile() +
  labs(title = "Relationship between Income Level, Year, & Health Expenditure 
       (% of GDP)",
       x = "Year",
       y = "Income",
       fill = "Health GDP") +
  scale_fill_viridis(direction=-1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  scale_y_discrete(limits = c("Low income", "Lower middle income", "Upper middle income", "High income"))

  
```

